# -*- coding: utf-8 -*-
"""Ecommerce Customer Support Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s0Qga3CpP2OcEjEcg5k0iYLdr5mlVR5p
"""

! pip install openai==0.28

! pip install langchain

!pip install langchain_community

import openai
import langchain
from langchain.llms import OpenAI
import os

openai.api_key = '<openai-api-key>'

def get_api_response(prompt:str) -> str | None:
    text: str | None = None

    try:
        response: dict = openai.Completion.create(
            model = 'gpt-3.5-turbo-instruct',
            prompt = prompt,
            temperature = 0.9,
            max_tokens = 150,
            top_p = 1, #alt to temperature
            frequency_penalty = 0,
            presence_penalty = 0.6,
            stop = [' Human:', ' AI:']
        )

        choices: dict = response.get('choices')[0]
        text = choices.get('text')

    except Exception as e:
        print('ERROR:', e)

    return text

print(get_api_response("What is the capital of France?"))

def update_list(message: str, pr = list[str]):
    pr.append(message)

def create_prompt(message: str, pr: list[str]) -> str:
    p_message: str = f'\nHuman: {message}'
    update_list(p_message, pr)
    prompt: str = ''.join(pr)
    return prompt

def get_bot_response(message: str, pr = list[str]) -> str:
    prompt: str = create_prompt(message, pr)
    bot_resp: str = get_api_response(prompt)

    if bot_resp:
        update_list(bot_resp, pr)
        pos: int = bot_resp.find('\nAI: ')
        bot_resp = bot_resp[pos + 5:]
    else:
        bot_resp = "Error: Something is wrong"

    return bot_resp

def main():
    prompt_list:list[str] = ['You are a chatbot for an e-commerce website',
    '\nHuman: Hello',
    '\nAI: Hello! I am your assistant. How may I help you today?']

    while True:
      user_input: str = input('Customer: ')
      response: str = get_bot_response(user_input, prompt_list)
      print(f'Assistant: {response}')

if __name__ == '__main__':
    main()

