# -*- coding: utf-8 -*-
"""Sentiment Analysis and Aspects

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17penOsPv-oPWAmHt6IQkyaKBiy35S_qt
"""

! pip install openai

! pip install langchain
! pip install langchain_community

import openai
import langchain
from langchain.llms import OpenAI
import os

openai.api_key = '<openai-api-key>'

rev = open("reviews a little life.txt", "r")

text = rev.read()

print(text)

def sentiment_analysis_by_bot(text_analysis):
  completion = openai.completions.create(
      model = 'gpt-3.5-turbo-instruct',
      prompt = (f'Sentiment analysis: {text_analysis}'),
      max_tokens = 5,
      temperature = 0.5
  )

  return completion.choices[0].text.strip()

def aspect_analysis_by_bot(text_analysis):
  completion = openai.completions.create(
      model = 'gpt-3.5-turbo-instruct',
      prompt = (f'Aspects analysis: {text_analysis}'),
      max_tokens = 10,
      temperature = 0.5
  )

  return completion.choices[0].text.strip()

with open("reviews a little life.txt", "r") as f:
  for index, review in enumerate(f):
    sentiment = sentiment_analysis_by_bot(review)
    aspect = aspect_analysis_by_bot(review)
    print(f"Review {index+1} is as follows: ")
    print(f"Sentiment: {sentiment}")
    print(f"\n")
    print(f"Aspects: {aspect}")
    print(f"\n\n")

with open("reviews a little life.txt", "r") as f:
  with open("output.txt", "w") as op:
    for index, review in enumerate(f):
      sentiment = sentiment_analysis_by_bot(review)
      aspect = aspect_analysis_by_bot(review)
      op.write(f"Review {index+1} is as follows: ")
      op.write(f"Sentiment: {sentiment}")
      op.write(f"\n")
      op.write(f"Aspects: {aspect}")
      op.write(f"\n\n")